permalink: /:title/
ftp_host: ftp.soulislove.com
ftp_dir: /
production_url : http://sitespeed.io
# options for _layouts/compress.html
compress_html:
  clippings: all
  endings: all
  ignore:
    #envs: [development]
